### PR TITLE
Add .rubocop.yml to template

### PR DESCRIPTION
**Pull request by jelaniwoods**
#69 

Adds `.rubocop.yml` file for all generated Rails apps.
Adds `rubocop-rails` and `rubocop-perfomance` gems.

I made changes to the following files that better adhere to Rubocop styles:
- `app/admin/dashboard`
- `lib/tasks/dev.rake`
- `config/initializers/devise.rb`
- `config/initializers/active_admin.rb`
- `config/initializers/nicer_errors.rb`
- `db/seeds`

### CODE REVIEW

**Comment by raghubetina** [comment]
Hm. To make this easier to discuss, can you throw up the vanilla version of `.rubocop.yml` somewhere, and then make a PR with your proposed changes for the AppDev version of `.rubocop.yml`, so we have a meaningful diff?

**Comment by jelaniwoods** [comment]
@raghubetina by "vanila" `.rubocop.yml` do you mean like [thoughtbot's file](https://github.com/thoughtbot/guides/blob/master/style/ruby/.rubocop.yml) or like the [default file from `rubocop-hq`](https://github.com/rubocop-hq/rubocop/blob/master/config/default.yml)

**Comment by raghubetina** [comment]
@jelaniwoods Hmm, good question. I sort of like the idea of starting from the _vanilla_ vanilla one, rubocop-hq's, and developing our own opinionated version. However I don't know how much we've been coasting off of thoughtbot's until now, maybe they've already done a ton of work. It might be instructive to first look at a diff between rubocop-hq's and thoughtbot's?

**Comment by jelaniwoods** [comment]
@raghubetina Sure. I made a pull request between the rubocop-hq's and thoughtbot's configuration file here appdev-projects/style#1

**Pull request closed without merging**
